version: "3.9"
  
services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init_db/:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
      - ./BDSnowflake/origin_data:/csv_data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d star"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped